# Generated by Django 4.2 on 2023-04-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.service'),
        ),
    ]
