# Generated by Django 4.2 on 2023-04-29 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement', '0002_alter_servicerate_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.service'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerate',
            unique_together={('user', 'service')},
        ),
    ]
