# Generated by Django 4.2 on 2023-04-28 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhtsappCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.TextField()),
                ('message', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='wapp_camp_img/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='wapp_camp_img/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='wapp_camp_img/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='wapp_camp_img/')),
                ('video', models.FileField(blank=True, null=True, upload_to='wapp_camp_video/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='wapp_camp_pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Submitted', max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
