# Generated by Django 4.2 on 2023-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whtsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whtsappcampaign',
            name='status',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Rejected', 'Rejected'), ('Stopped', 'Stopped'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Submitted', max_length=20, null=True),
        ),
    ]
